### ISSUE TITLE
add replication option for init?

### ISSUE THREAD

**Issue by mikeatlas** [MazeMap/Leaflet.TileLayer.PouchDBCached#1]
Hi Iván! 

We're testing out your plugin today since it seems one of our tile server providers is experiencing significant network delays at the moment. Any chance you might add an option for the [replication](http://pouchdb.com/api.html#replication) aspect of PouchDB? It'd be neat if we could serve up cached versions of our reusable tiles from our own CouchDB server whenever possible in order to mitigate situations like we're experiencing right now.

Thanks,
Mike

**Comment by IvanSanchez** [comment]
Won't fix.

MapProxy is much better suited for that scenario.
