### ISSUE TITLE
PoachDBCached 0.1.0

### ISSUE THREAD

**Issue by siasd** [MazeMap/Leaflet.TileLayer.PouchDBCached#10]
Not sure if you will be supporting v0.1.0 for leaflet 0.7x, with the new realease of PoachDB 4.01 it seem that the tiles no longer saved to the DB? It still work fine with PDB v3.60

Thanks for a great plugin

**Comment by IvanSanchez** [comment]
No, unfortunately I don't have the time to support plugins for Leaflet 0.7.x.
