### ISSUE TITLE
Update bower.json?

### ISSUE THREAD

**Issue by kentr** [MazeMap/Leaflet.TileLayer.PouchDBCached#16]
The latest `Leaflet.TileLayer.PouchDBCached` uses Leaflet `1.0-beta1`, right?

Does it make sense to update `bower.json`?

Currently:

``` json
  "dependencies": {
    "leaflet": "~0.7.3",
    "pouchdb": "~3.3.1"
  }
```

**Comment by IvanSanchez** [comment]
This project does not use a `bower.json` file. Given that most devs are phasing out Bower in favour of NPM/yarn, I'd rather let it stay that way.
