### ISSUE TITLE
Does it work with mapbox maps?

### ISSUE THREAD

**Issue by etcware** [MazeMap/Leaflet.TileLayer.PouchDBCached#17]
I tried to integrate the library with mapbox but it doesn't seem to work.
To start I don't cached any tiles and my expectation is that it gets tiles from server but the map is incomplete.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by robindierckx** [comment]
For me it is working with mapbox

**Comment by IvanSanchez** [comment]
Unable to reproduce → closing.
