### ISSUE TITLE
demo dont work

### ISSUE THREAD

**Issue by tombtom** [MazeMap/Leaflet.TileLayer.PouchDBCached#18]
file
http://mazemap.github.io/Leaflet.TileLayer.PouchDBCached/bower_components/pouchdb/dist/pouchdb.js
not found

**Comment by hrishiballal** [comment]
From https://pouchdb.com/download.html

You can just change the pouch db URL to : https://cdn.jsdelivr.net/pouchdb/5.4.5/pouchdb.min.js

**Comment by IvanSanchez** [comment]
Fixed in 031d02b0999c5893aca0625af4c7e9beac66107c by pointing to `unpkg.com`
