### ISSUE TITLE
add support for L.mapbox.TileLayer?

### ISSUE THREAD

**Issue by mikeatlas** [MazeMap/Leaflet.TileLayer.PouchDBCached#2]
We're using a few MapBox tile layers; the [MapBox leaflet wrapper](https://github.com/mapbox/mapbox.js/blob/mb-pages/src/mapbox.js) extends [L.TileLayer](https://github.com/mapbox/mapbox.js/blob/mb-pages/src/tile_layer.js) to support some additional options and features unique to MapBox's tile server.

Any chance you might consider adding support to extend `L.mapbox.tileLayer` as well?

**Comment by mikeatlas** [comment]
Here's a quick stab at it in my fork: 

https://github.com/weftio/Leaflet.TileLayer.PouchDBCached/blob/master/L.TileLayer.PouchDBCached.js

I didn't try to get the WMS tile layer part working.

**Comment by IvanSanchez** [comment]
I think the right way to do this should be to extend the base L.TileLayer classby using the mixins pattern available in Leaflet. Will try to research the matter in a few days.

**Comment by mikeatlas** [comment]
I think that would be helpful. Other plugins also extend tileLayer and could benefit from this caching (and a replication db on our end). Another example is [Leaflet-OpenWeatherMap](https://github.com/buche/leaflet-openweathermap). Their tile server is terribly slow; weather updates from our perspective could be cached for 15min and shared in a replicated couchdb, for example  --- as a sort of tile server proxy, basically.

**Comment by IvanSanchez** [comment]
Personally, I'd set up instances of MapProxy (https://github.com/mapproxy/mapproxy) for that. A CouchDB tileserver seems... unoptimal for the job at hand, I think.

**Comment by mikeatlas** [comment]
Thanks for the MapProxy tip!

**Comment by IvanSanchez** [comment]
Yeah, mixins are the way to go if we want to not worry about subclasses of L.TileLayer. See bc2a388d

**Comment by mikeatlas** [comment]
Awesome. :+1:
