### ISSUE TITLE
Firefox and SecurityError

### ISSUE THREAD

**Issue by claudep** [MazeMap/Leaflet.TileLayer.PouchDBCached#20]
On Firefox, I'm getting the following errors:

```
SecurityError: The operation is insecure.
    var dataUrl = this._canvas.toDataURL(this.options.cacheFormat);
```

Any suggested workaround?

**Comment by IvanSanchez** [comment]
Your canvas is tainted.

https://github.com/MazeMap/Leaflet.TileLayer.PouchDBCached#cross-origin-resource-sharing
https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image

Also, please do not use this bug tracker as a channel for support.

**Comment by claudep** [comment]
Sorry :-( But this could be used as a FAQ entry in the README. Tell me if you are interested by a patch.

**Comment by IvanSanchez** [comment]
The CORS section on the README already covers that. If you feel the wording is inadequate, do send a PR.

**Comment by claudep** [comment]
By the way, it would be nice if the demo was working again, so as I could plainly see if my code was at fault or if it was a browser issue.
