### ISSUE TITLE
Comparing this with downloading tiles in advance

### ISSUE THREAD

**Issue by ghost** [MazeMap/Leaflet.TileLayer.PouchDBCached#40]
Hi,

I had task to use leaflet offline. For this my approach was to download tiles in png format in following fashion: ` {atlas_name}/{z}/{x}/{y}.png ` and use leaflet like:

`L.tileLayer('localfolder/atlasName/{z}/{x}/{y}.png', {    maxZoom: 16  }).addTo(mymap);`

But I have one problem with above approach, the size of tiles is too big. For example for geographic area I needed for zoom 14 the total size of tiles was 200MB.

My question is if I use TileLayer.PouchDBCached what advantages does it bring over above approach? does it use less space?

---

Also I assume when user uses this throughout time, the cache will store more and more tiles right? Is there a way to delete some entries in the cache? How long are they stored?

**Comment by nikolauskrismer** [comment]
How long tiles are cached depends on the cacheMaxAge parameter (defaults to 24h).

However, if you need smaller filesizes this plugin is not what you are looking for, since it just caches the tiles that you can also download by hand in png format. It does not reduce filesize.

Do you already know about vector tiles? Thats one good way I can think about when working offline and caring about filesizes....

**Comment by giorgi-m** [comment]
@nikolauskrismer 

> How long tiles are cached depends on the cacheMaxAge parameter (defaults to 24h).
So after 24 hours they are deleted?

> Do you already know about vector tiles? Thats one good way I can think about when working offline and caring about filesizes....
No, I don't. Can you provide some links about vector tiles/offline usage?

**Comment by ghost** [comment]
@nikolauskrismer 

> How long tiles are cached depends on the cacheMaxAge parameter (defaults to 24h).

So after 24 hours they are deleted?

I managed to download a file of vector tiles, I also found [this ](https://github.com/Leaflet/Leaflet.VectorGrid#docs) for displaying vector tiles, however it says: "L.VectorGrid.Protobuf for displaying vector tiles from an online tile server". I need to use it in offline mode however. Do you know of workaround for this limitation?

**Comment by nikolauskrismer** [comment]
Hmm... if they are deleted immediately after 24hours... you can not tell that for sure... I guess that it depends on the size of your browsers cache (and maybe on some additional factors).
What you can tell for sure is that are re-requested from the server if you view them again after 24 hours

For additional information the OSM wiki on vector tiles might be a good starting point:
https://wiki.openstreetmap.org/wiki/Vector_tiles

This question on gis.stackexchange also looks promising. It uses vector tiles downloaded from openmaptiles.org:
https://gis.stackexchange.com/questions/254683/showing-offline-map-downloaded-from-openmaptiles-com-with-openlayers
