### ISSUE TITLE
Chrome blocking and pouchdb location.

### ISSUE THREAD

**Issue by bkboggy** [MazeMap/Leaflet.TileLayer.PouchDBCached#5]
While using this with IE, it asked me if I wanted to unblock content, and after doing so, everything worked fine.  However, I would like to use Chrome's dev tools (since IE doesn't have the best ones) to monitor local storage... however, it's blocking this script.  All I see is gray map whenever I set use of cache to true. 

In a separate, but relatable question... where is pouchdb stored?  I would like to cache the tiles and redistribute to several machines.

Thanks,

BK

**Comment by IvanSanchez** [comment]
What do you see in Chrome's dev console and network monitor? Is your webpage being served through HTTP or HTTPS? Are your tiles being served by HTTP or HTTPS?

See also http://stackoverflow.com/questions/9972049/cross-origin-data-in-html5-canvas

> In a separate, but related question... where is pouchdb stored?

RTFM: http://pouchdb.com/adapters.html

> I would like to cache the tiles and redistribute to several machines.

Then this is the wrong tool. See https://github.com/mapproxy/mapproxy (see #2)

**Comment by bkboggy** [comment]
Except for the fact that MapProxy requires installation and I can't install it on every client..... since I'm seeking an offline solution, having them connected to a server that has this is not an option either.

**Comment by IvanSanchez** [comment]
You don't install mapproxy on every client. You install it on one of your servers, and have all clients seed from there.

Once again: what's in chrome's dev console and network monitor? This smells like a cross-origin policy issue, and there should be something on the logs.

**Comment by bkboggy** [comment]
But like I said... if clients are offline, how would they be able to connect?  I'm looking for an offline solution. 

As far as Chrome, I get this:

Image from origin 'http://192.168.0.24' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

**Comment by IvanSanchez** [comment]
This library is meant for clients which are able to connect to the server, cache the tiles, then go offline. That is my use case, and I have no interest on functionality beyond that. If you want to extend this code  in order to export/import a cache, go ahead.

If you are planning on distributing a completely offline application along with tiles, the solution then is to pack your tiles as a MBtiles file (or whatever) and use that.

> No 'Access-Control-Allow-Origin' header is present on the requested resource

Well, make sure that your tile server adds a `Access-Control-Allow-Origin: *` header to every tile served.

**Comment by bkboggy** [comment]
Thanks.
