### ISSUE TITLE
will the project be further developed?

### ISSUE THREAD

**Issue by strukturart** [MazeMap/Leaflet.TileLayer.PouchDBCached#50]

**Comment by nikolauskrismer** [comment]
Hi @strukturart ,

at the moment this is not really well maintained.
One of the reasons is that I cam not able to dedicate the same amount of time to the project as I was some years ago.
Anyways, I am happy to review and merge PRs where I can. Please just keep in mind that this is something that I am doing besides my full-time job, so don't expect any communication of deadlines or such things (from my side... not sure about MazeMap)...

Greetings,
Niko

**Comment by strukturart** [comment]
thank you for writing the plugin! I use it here in my osm app for KaiOs: https://github.com/strukturart/o.map
//
Everything works, only with `useOnlyCache: true`, no tiles are displayed. i wanted to use it to check if you downloaded all the necessary map data before going on a tour.

**Comment by strukturart** [comment]
or am I misunderstanding `useOnlyCache: true` and you can't only see the local tiles?
