### ISSUE TITLE
Angular-leaflet-directive integration

### ISSUE THREAD

**Issue by nurseybushc** [MazeMap/Leaflet.TileLayer.PouchDBCached#7]
Hello, I was wondering if there is a way to integrate this plugin with angular leaflet directive? Thanks very much

**Comment by IvanSanchez** [comment]
The answer is "yes". You should rephrase your question.

**Comment by nurseybushc** [comment]
Sorry about that haha. How would I go about integrating it with angular-leaflet-directive? Right now I have this in my angular.extend : 

```
layers: {
      baselayers: {
        osm: {
          name: 'OpenStreetMap',
          url: 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
          type: 'xyz',
          useCache: true
        }
      }
```

Thanks again

**Comment by IvanSanchez** [comment]
The issue is that I've never used Angular, and I even haven't seen the angular-leaflet-directive. So while it might be possible, I wouldn't know where to start.
