### ISSUE TITLE
Leaflet 1.0 beta 1

### ISSUE THREAD

**Issue by clemenslermen** [MazeMap/Leaflet.TileLayer.PouchDBCached#9]
Do you plan to do an update for the upcoming Leaflet 1.0?
As the performance there is really nice and i totally love your plugin, it would be cool! 
At the moment it seems, that the plugin is somehow working, but not storing the tiles

**Comment by IvanSanchez** [comment]
@clemenslermen Please check that 23f6c6ca works as expected.

**Comment by eiriksfa** [comment]
Seed function didn't work for me (same leaflet beta version?).
The following code works (not thoroughly tested): 

(code removed, see pull request #11)

**Comment by IvanSanchez** [comment]
@eiriksfa Don't put the whole thing on a comment. We have diffs and pull requests for that kind of thing.

**Comment by eiriksfa** [comment]
Okay, will create a fork

**Comment by IvanSanchez** [comment]
Closed via #11
